### ISSUE TITLE
Can convert2torch.py convert fine tined models?

### ISSUE THREAD

**Issue by htcml** [NormXU/ERNIE-Layout-Pytorch#19]
I used the fine tune instruction to produce a fine-tuned model on funsd:
[https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layout#41-key-information-extraction](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layout#41-key-information-extraction)

Can convert2torch.py convert this fne-tuned model?

**Comment by NormXU** [comment]
Sure, convert2torch.py should work on your fine-tuned model

**Comment by htcml** [comment]
Thank you!
