### ISSUE TITLE
Could you make test_ernie_qa runnable?

### ISSUE THREAD

**Issue by calvinzhan** [NormXU/ERNIE-Layout-Pytorch#2]
Great work, Norm!

I would like to debug the model logic by running test_ernie_qa, but currently both pretrain_torch_model_or_path and doc_imag_path are mocked. 

I can assign pretrain_torch_model_or_path to "Norm/ERNIE-Layout-Pytorch", but miss the image. Could you upload the image, so that we can run the case successfully?

Thanks a lot!

**Comment by NormXU** [comment]
Thanks for your suggestion. Any image should be fine if you just want to debug `test_ernie_qa.py`. 

[This](https://huggingface.co/Norm/ERNIE-Layout-Pytorch/tree/main) is a pretrained model without fine-tuning on any downstream tasks. So directly loading this model and running `test_ernie_qa.py` on a specific task will return unsatisfactory results. You can refer to this script and adapt it to your own dataset.
