### ISSUE TITLE
Which version of Flash Attention has been used in this project?

### ISSUE THREAD

**Issue by 14H034160212** [NormXU/ERNIE-Layout-Pytorch#22]
Hi,

I find the project is very interesting. Can I ask which Flash Attention has been used in this project?

From the official flash attention project, they have provided flash attention and flash attention v2. 
https://github.com/Dao-AILab/flash-attention

Kind regards,
Qiming

**Comment by NormXU** [comment]
@14H034160212 Thank you for your interest. I used PyTorch's [Scaled Dot-Product Attention](https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html) to speed up inference speed instead of Dao's implementations.

**Comment by 14H034160212** [comment]
![image](https://github.com/NormXU/ERNIE-Layout-Pytorch/assets/23516191/97eb435f-5847-403a-812b-1e5a1c48b619)
Do you use the FlashAttention-2 that implemented here? There are three supported implementations of scaled dot product attention.
