### ISSUE TITLE
diff between paddle and torch

### ISSUE THREAD

**Issue by WallE-Chang** [NormXU/ERNIE-Layout-Pytorch#3]
Hi, NormXU
        Have you compared the difference of ernie-layout output between paddle version and pytorch version ?

**Comment by NormXU** [comment]
Hi Chang,

I have compared the ernie-layout output between the Paddle version and Pytorch version with the same input, and the difference between them can be ignored. Actually, I barely translated [ paddle verion ](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie_layout/modeling.py) line by line and converted all the weights Paddle released into Pytorch-style.

**Comment by WallE-Chang** [comment]
nice work !! Can you share the python file which you use to compared the ernie-layout output between the Paddle version and Pytorch version with the same input ? It is important to prove your work

**Comment by WallE-Chang** [comment]
By the way,  the convert2torch file may have some bugs. model.ernie_layout.init_config can not be dumped. I fix it by following code: 
```python
with open(os.path.join(pretrain_torch_model_or_path, "config.json"), "w") as outfile:
    config = model.ernie_layout.init_config
    config['init_args'] = (config['init_args'][0].__dict__)
    outfile.write(json.dumps(config))

```

**Comment by NormXU** [comment]
I add this [script](https://github.com/NormXU/ERNIE-Layout-Pytorch/blob/main/examples/compare_output.py) to compare the output between the two versions. Hope this can be helpful.  

The MSE between two versions: eps of pooled output: 0.004253871738910675; eps of sequence output: 3.5654803762219522e-12.

**Comment by WallE-Chang** [comment]
Your work is very excellent, and can I add your wechat  for further discussion?

**Comment by NormXU** [comment]
Thank you. Please feel free to post any questions you may have here. I hope others will be able to review our discussion.
