### ISSUE TITLE
DocVQA fine-tuning example?

### ISSUE THREAD

**Issue by JP-Leite** [NormXU/ERNIE-Layout-Pytorch#9]
Are there any examples of how we can fine tune with the DocVQA dataset?

**Comment by NormXU** [comment]
[Here](https://github.com/NormXU/ERNIE-Layout-Pytorch/blob/main/examples/test_ernie_qa.py) is a simple example of applying ERNIE on the VQA task.

Here is another complete [repo](https://github.com/allanj/LayoutLMv3-DocVQA) of fine-tuning on DocVQA that I strongly recommend reading. You can replace the tokenizer and model with ERNIE I provided and see  train a model for your own task.
